package ai

import (
	"context"
	"fmt"

	"github.com/sashabaranov/go-openai"
)

type OpenAIProvider struct {
	client *openai.Client
	model  string
}

func NewOpenAIProvider(apiKey string, model string) (*OpenAIProvider, error) {
	if model == "" {
		model = openai.GPT4o // default
	}

	client := openai.NewClient(apiKey)

	return &OpenAIProvider{
		client: client,
		model:  model,
	}, nil
}

func (o *OpenAIProvider) GenerateContent(ctx context.Context, systemPrompt, userPrompt string, temperature float32) (string, error) {
	resp, err := o.client.CreateChatCompletion(
		ctx,
		openai.ChatCompletionRequest{
			Model: o.model,
			Messages: []openai.ChatCompletionMessage{
				{
					Role:    openai.ChatMessageRoleSystem,
					Content: systemPrompt,
				},
				{
					Role:    openai.ChatMessageRoleUser,
					Content: userPrompt,
				},
			},
			Temperature: temperature,
		},
	)

	if err != nil {
		return "", fmt.Errorf("failed to generate content: %w", err)
	}

	if len(resp.Choices) == 0 {
		return "", fmt.Errorf("no content generated by OpenAI")
	}

	return resp.Choices[0].Message.Content, nil
}

func (o *OpenAIProvider) Close() error {
	// OpenAI client doesn't need explicit closing
	return nil
}
